"""empty message

Revision ID: b86d98d73ae7
Revises: a1aca12ae6bc
Create Date: 2024-05-20 11:32:00.031581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86d98d73ae7'
down_revision = 'a1aca12ae6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('service_needed', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_request_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_request_timestamp'))

    op.drop_table('customer_request')
    # ### end Alembic commands ###
